### ISSUE TITLE
Unable to install chart from repo

### ISSUE THREAD

**Issue by pavel-berka** [getlago/lago-helm-charts#120]
Im trying to install Lago via Helm chart but it fails.

Adding Helm repo and listing it works fine: 
```bash
$ helm repo add lago https://charts.getlago.com/
"lago" has been added to your repositories

$ helm repo update 
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "lago" chart repository
Update Complete. ⎈Happy Helming!⎈

$ helm search repo lago
NAME            CHART VERSION   APP VERSION                     DESCRIPTION                                       
lago/lago       1.15.0          1.15.0                          the Lago open source billing app                  
lago/minio      5.2.0           RELEASE.2024-04-18T19-09-19Z    High Performance Object Storage                   
lago/postgresql 13.2.2          16.0.0                          PostgreSQL (Postgres) is an open source object-...
lago/redis      18.2.1          7.2.3                           Redis(R) is an open source, advanced key-value ...
```

But acutally trying to install it throws error that the chart does not exist (all four charts):
```bash
$ helm install my-lago lago/lago
Error: INSTALLATION FAILED: failed to fetch https://getlago.github.io/charts/charts/lago-1.15.0.tgz : 404 Not Found
```

Helm used:
```bash
$ helm version --short
v3.14.3
```

**Comment by jdenquin** [comment]
👋  @pavel-berka should work now!

**Comment by pavel-berka** [comment]
Thanks for swift reaction!

I still get an error, different URL though:
```bash
$ helm install my-lago lago/lago
Error: INSTALLATION FAILED: failed to fetch https://getlago.github.io/charts/lago-1.15.0.tgz : 404 Not Found
```

I tried to download the URL directly and failed
```bash
$ wget -nv https://getlago.github.io/charts/lago-1.15.0.tgz
https://getlago.github.io/charts/lago-1.15.0.tgz:
2024-11-08 14:50:07 ERROR 404: Not Found.
```
But then tried to download the archive from the hostname set as Helm repository and succeeded!
```bash
$ wget -nv https://charts.getlago.com/charts/lago-1.15.0.tgz
2024-11-08 14:46:06 URL:https://charts.getlago.com/charts/lago-1.15.0.tgz [1688907/1688907] -> "lago-1.15.0.tgz" [1]

$ file lago-1.15.0.tgz 
lago-1.15.0.tgz: gzip compressed data, extra field, has comment, original size modulo 2^32 4822016
```

Maybe the URL you changed should be `https://charts.getlago.com` and not `https://getlago.github.io`?
I see the former is an alias for the latter but the canonical one does not work :monocle_face: 
```bash
$ host charts.getlago.com
charts.getlago.com is an alias for getlago.github.io.
[...]
```

**Comment by jdenquin** [comment]
should work now!

**Comment by Wingrammer** [comment]
It's still not working

**Comment by pavel-berka** [comment]
I can confirm that it does not work. Probable cause might be missing `lago` archive in `charts` dir?
https://github.com/getlago/lago-helm-charts/tree/main/charts
I can install `lago/redis` but `lago/lago`  fails with the same 404 error as before.

**Comment by pavel-berka** [comment]
The chart is found, thanks!

But I encountered another issue - installation complains about missing value even though I set it
Via CLI args:
```bash
$ helm install my-lago lago/lago --set apiUrl=example.com --set frontUrl=example.com 
Error: INSTALLATION FAILED: execution error at (lago/charts/lago/templates/worker-deployment.yaml:68:24): apiUrl value is required
```
Via file:
```bash
$ cat ./lago-values.yaml 
apiUrl: example.org
frontUrl: example.org

$ helm install my-lago lago/lago --values ./lago-values.yaml 
Error: INSTALLATION FAILED: execution error at (lago/charts/lago/templates/worker-deployment.yaml:68:24): apiUrl value is required
```

Even just templating does not work:
```bash
$ helm template my-lago lago/lago --set apiUrl=example.com --set frontUrl=example.com 
Error: execution error at (lago/charts/lago/templates/worker-deployment.yaml:68:24): apiUrl value is required

Use --debug flag to render out invalid YAML


$ helm template my-lago lago/lago --set apiUrl=example.com --set frontUrl=example.com --debug
install.go:224: 2024-11-12 11:46:55.753385252 +0100 CET m=+0.029909020 [debug] Original chart version: ""
install.go:241: 2024-11-12 11:46:56.182276603 +0100 CET m=+0.458799882 [debug] CHART PATH: /home/pb/.cache/helm/repository/lago-1.15.0.tgz


Error: execution error at (lago/charts/lago/templates/worker-deployment.yaml:68:24): apiUrl value is required
helm.go:86: 2024-11-12 11:46:56.320161579 +0100 CET m=+0.596685347 [debug] execution error at (lago/charts/lago/templates/worker-deployment.yaml:68:24): apiUrl value is required
```

My Helm seems to work fine, trying it with `lago/redis` outputs the YAML set:
```bash
$ helm template my-lago lago/redis | head
---
# Source: redis/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: my-lago-redis
  namespace: "default"
  labels:
    app.kubernetes.io/instance: my-lago
```

Could you please advise me on how to solve this issue?

**Comment by electrosenpai** [comment]
Hi there,

Thank you for reaching out and for the detailed information!

The issue you're encountering is likely due to the requirement of fully qualified paths for setting values. Please try installing the chart with the following command:

```
helm install my-lago lago/lago --version 1.15.0 --values values.yaml --set lago.apiUrl=https://api.domain.tld --set lago.frontUrl=https://app.domain.tld
```

This prefix (`lago.apiUrl` and `lago.frontUrl`) should ensure that Helm locates the variables correctly.

Additionally, we recommend using the Git repository directly for the time being. Although we’re actively working on documentation for helm.getlago.com, it’s not fully available yet.

Let us know if this resolves the issue or if you need further assistance!

**Comment by pavel-berka** [comment]
I am still unable to install it even when using full variable path:
```bash
$ helm template my-lago lago/lago --version 1.15.0 --set lago.apiUrl=https://api.domain.tld --set lago.frontUrl=https://app.domain.tld --debug
install.go:218: [debug] Original chart version: "1.15.0"
install.go:235: [debug] CHART PATH: /home/pb/.cache/helm/repository/lago-1.15.0.tgz


Error: execution error at (lago/templates/worker-deployment.yaml:68:24): apiUrl value is required
helm.go:84: [debug] execution error at (lago/templates/worker-deployment.yaml:68:24): apiUrl value is required
```

But I understand the chart repo is not yet tuned for "production-ready" usage so I'll stick with git repo approach.

Anyway, thanks for your time!

**Comment by electrosenpai** [comment]
> I am still unable to install it even when using full variable path:
> 
> ```shell
> $ helm template my-lago lago/lago --version 1.15.0 --set lago.apiUrl=https://api.domain.tld --set lago.frontUrl=https://app.domain.tld --debug
> install.go:218: [debug] Original chart version: "1.15.0"
> install.go:235: [debug] CHART PATH: /home/pb/.cache/helm/repository/lago-1.15.0.tgz
> 
> 
> Error: execution error at (lago/templates/worker-deployment.yaml:68:24): apiUrl value is required
> helm.go:84: [debug] execution error at (lago/templates/worker-deployment.yaml:68:24): apiUrl value is required
> ```
> 
> But I understand the chart repo is not yet tuned for "production-ready" usage so I'll stick with git repo approach.
> 
> Anyway, thanks for your time!

You're very welcome! I’ll add a ticket to our backlog to address this issue as soon as possible. I'll go ahead and close this issue for now, but please don’t hesitate to open another if you run into any issues with the Git repository.

**Comment by electrosenpai** [comment]
Hello @pavel-berka.

It should be good now !

```
➜ helm install old-lago lago/lago --version 1.15.2 --values value_old.yaml
NAME: old-lago
LAST DEPLOYED: Wed Nov 20 10:51:33 2024
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
```

**Comment by pavel-berka** [comment]
I can confirm it looks OK, thanks!
```
$ helm install my-lago lago/lago --set apiUrl=https://example.com --set frontUrl=https://example.com
NAME: my-lago
LAST DEPLOYED: Thu Nov 21 17:15:38 2024
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
```

**Comment by electrosenpai** [comment]
You're welcome :)
